dir = "@SpyderAddons";
name = "Spyder Addons";
picture = "x\spyderaddons\addons\main\Logo.paa";
actionName = "";
action = "http://steamcommunity.com/sharedfiles/filedetails/?id=579263829";
description = "A collection of modules and scripts designed to aid mission makers in adding depth to their missions.";
hideName = 1;
hidePicture = 0;
logo = "x\spyderaddons\addons\main\Logo.paa";
logoOver = "x\spyderaddons\addons\main\Logo.paa";
tooltip = "Spyder Addons";
tooltipOwned = "Spyder Addons Owned!";
overview = "A collection of modules and scripts designed to aid mission makers in adding depth to their missions.";
author = "SpyderBlack723";
overviewPicture = "\x\spyderaddons\addons\main\Logo.paa";
overviewText = "Spyder Addons - Giving missions depth";
overviewFootnote = "Created by SpyderBlack723";